### PR TITLE
Refactor memories to conversations

### LINKED ISSUE #1311: rename memory to converstaion
conversations are conversations, they are not memories, it's dumb

### PR DESCRIPTION
**Pull request by mdmohsin7**
Closes #1311 

- [x] Rename `memories` to `conversations` everywhere

Note: This PR does not rename `memory` to `conversation` for mixpanel events

### CODE REVIEW

**Comment by beastoin** [comment]
man @mdmohsin7, could you split this ticket into two or more separated tickets(single responsibility) then add the TODOs section to each ticket so that i could understand more clearly about what should be reviewed 😌

**Comment by mdmohsin7** [comment]
Alright let me @beastoin

**Comment by beastoin** [comment]
nice work. resolve the conflict pls sir @mdmohsin7

**Comment by mdmohsin7** [comment]
Done! Pls check @beastoin

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳

**Pull request merged**
