### PR TITLE
handle notification when app in a terminated state & in background

### PR DESCRIPTION
**Pull request by chiemduong97**
#1328

### CODE REVIEW

**Comment by beastoin** [comment]
we already have the notification tap handling at line :253 , pls double check if it works as expected so we could close this PR.

**Comment by chiemduong97** [comment]
> we already have the notification tap handling at line :253 , pls double check if it works as expected so we could close this PR.

yes I tested and it works as expected

**Comment by beastoin** [comment]
i mean does it still work as expected if i don't merge this PR ? @chiemduong97

**Comment by chiemduong97** [comment]
@beastoin no, if don't merge this PR it only handle receiving notifications when the app in foreground. This PR is handle receiving notifications app in background and ended state.

**Comment by beastoin** [comment]
nice, got. so:

1/ why do you need post frame callback here https://github.com/BasedHardware/omi/pull/1381/files#diff-d800130e2b6c0934dd0ec580def15005703af8780651d1cfebf79d7886e5bc00R167 ; you could find the old version at  https://github.com/BasedHardware/omi/pull/1379/files
2/ please check the notificaiton handling logic at https://github.com/BasedHardware/omi/blob/main/app/lib/services/notifications.dart#L254 , you could re-use it.
3/ as i mentioned in our Telegram discussion, if there's a duplicated user's tap event handling this code block would make the feature failed https://github.com/BasedHardware/omi/main/1381/files#diff-d800130e2b6c0934dd0ec580def15005703af8780651d1cfebf79d7886e5bc00 , for example:
 - the first initState was called then the SharedPreferencesUtil().pageToShowFromNotification set to 0
 - then the second initState was called then page controller will navigate the user to Home, not Chat

@chiemduong97 please check these cases 😌

**Comment by chiemduong97** [comment]
1/because getInitialMessage() will be called right after opening the application from the notification when the application in end state, at this time the build process is not completed so we need to wait for the build process to complete. But when the app is in the background or foreground, the build process has completed before so there is no need.
2/ yes, I will re-use it 
3/ It not duplicated. because FirebaseMessaging.onMessage only run if app in foreground, at this time it is local notification. while app in background and end state it is push notification.
@beastoin

**Pull request closed without merging**
