### PR TITLE
Integrate datadog to backend for traces and logs

### PR DESCRIPTION
**Pull request by thainguyensunya**
Issue #1217 

**Key changes:**

- Add ddtrace library
- Wrap application to datadog serverless-init to collect traces and logs

### CODE REVIEW

**Comment by beastoin** [comment]
Great a @thainguyensunya , could you share a image / demo how does it look like with the dev env ?

1/ Could we use Dd as an option for Docker deployment ? You know that we are an opensource, someone don't really need Dd for their backend deployment

**Comment by thainguyensunya** [comment]
Screenshot 2024-11-14 at 10 57 18 AM
Screenshot 2024-11-14 at 10 56 37 AM
Screenshot 2024-11-14 at 10 58 35 AM
Screenshot 2024-11-14 at 10 56 17 AM

**Comment by beastoin** [comment]
lgtm @thainguyensunya 🥳

**Comment by beastoin** [comment]
Next, please provide w/ steps to deploy then we push it to production :)

**Pull request merged**
