### PR TITLE
[FIX] GPT API in AHDA and examples

### PR DESCRIPTION
**Pull request by Neotastisch**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new function for sending debug messages to enhance error tracking.
	- Added an asynchronous route for processing incoming data with improved validation and session management.

- **Bug Fixes**
	- Enhanced error handling and logging for existing functions to improve traceability.

- **Documentation**
	- Updated method names for clarity and consistency.

### CODE REVIEW

**Comment by beastoin** [comment]
man @Neotastisch help me with updating ahda codes, use snake case instead of camel case.

**Comment by beastoin** [comment]
and pls explain why do you need the backend changes ?

**Comment by neooriginal** [comment]
> man @Neotastisch help me with updating ahda codes, use snake case instead of camel case.

originally i was trying to fix the real time transcription. i reverted the changes though

**Comment by beastoin** [comment]
> > man @Neotastisch help me with updating ahda codes, use snake case instead of camel case.
> 
> originally i was trying to fix the real time transcription. i reverted the changes though

still see /backend changes, discard it pls

**Comment by neooriginal** [comment]
> > > man @Neotastisch help me with updating ahda codes, use snake case instead of camel case.
> > 
> > 
> > originally i was trying to fix the real time transcription. i reverted the changes though
> 
> still see /backend changes, discard it pls

done

**Comment by beastoin** [comment]
lgtm @Neotastisch 🚀 , ready on prod.

**Pull request merged**
