### PR TITLE
Added Deep Sleep functionality

### PR DESCRIPTION
**Pull request by Neotastisch**
Hey, 
First off please be patient with me since i have no experience with this and made this just using google and a few hours of searching through stackoverflow.

This code adds a deep sleep functionality using the 4. and 5. gpio pin (for dev kit v2). if there are any problems with the code lmk. you are also free to use this code as a new pr.

hope this helps

### CODE REVIEW

**Comment by francip** [comment]
@kevvz and you should talk and figure out the button handling, because it seems there's going to be conflict between this PR handling long press and https://github.com/BasedHardware/Omi/pull/576

**Comment by francip** [comment]
We are not using firmware 1.5, all the firmware changes have been made in firmware 1.0.

That said, your deep_sleep code still can be integrated, but you might have to wait for https://github.com/BasedHardware/Omi/pull/576 and add it to it.

**Comment by kevvz** [comment]
Yes, I think with my code you can easily slip in the deep sleep code. My code uses a "fancy" state machine so I think you can slip in the function somewhere without changing too much. If you want I can write a state table so it would be easier to see where you could put it.

**Comment by neooriginal** [comment]
> Yes, I think with my code you can easily slip in the deep sleep code. My code uses a "fancy" state machine so I think you can slip in the function somewhere without changing too much. If you want I can write a state table so it would be easier to see where you could put it.

sure thanks :) Do you perhaps have discord for better communication? @neo_original is my tag

**Comment by neooriginal** [comment]
Build is successfull. If anyone wants to test it for me, please build it yourself since i cant attach uf2

Cant test it myself yet

**Comment by neooriginal** [comment]
Seems like shutting down works. Any idea how to start it?

**Comment by vincentkoc** [comment]
@Neotastisch We should probably wait for other hardware feature PRs like SD Card, Audio, Buttons, and Accelerometer working first. You can also setup a sleep pin-out in overlay and use in-built battery management elements in the actual libraries to cycle down components fully too. See: https://docs.zephyrproject.org/latest/services/pm/device.html

Not sure how you are handling wake-up without a force restart?

**Comment by neooriginal** [comment]
> @Neotastisch We should probably wait for other hardware feature PRs like SD Card, Audio, Buttons, and Accelerometer working first. You can also setup a sleep pin-out in overlay and use in-built battery management elements in the actual libraries to cycle down components fully too. See: https://docs.zephyrproject.org/latest/services/pm/device.html
> 
> Not sure how you are handling wake-up without a force restart?

still working on that. this pr also uses the new button handling so when its done it should work together seamlessly

**Comment by neooriginal** [comment]
i killed my friend :( cant afford a new one.

anyone taking over this? Sorry

**Comment by neooriginal** [comment]
aw man really sad, wanted to contribute

**Comment by josancamon19** [comment]
@Neotastisch I think @ebowwa on discord reached out for sending you a new one, did you already sort that out?

**Comment by Neotastisch** [comment]
> @Neotastisch I think @ebowwa on discord reached out for sending you a new one, did you already sort that out?

Not yet, would really appreciate that though :)

**Comment by neooriginal** [comment]
> @Neotastisch I think @ebowwa on discord reached out for sending you a new one, did you already sort that out?

I build mine myself, so probably not right?

**Comment by josancamon19** [comment]
@kevvz @ro-kirchev can you guys check if this is going well? thanks

**Comment by ebowwa** [comment]
@Joan its an open-source build, where likely the button was broken off the
board. 

Replacement is handled.

**Comment by neooriginal** [comment]
> @kevvz @ro-kirchev can you guys check if this is going well? thanks

I would not check it yet, it's not done yet. I pushed an untested update recently but could not test it since it broke

**Comment by neooriginal** [comment]
Will redo it later

**Pull request closed without merging**
