### PR TITLE
Add back trigger memory created integration

### PR DESCRIPTION
**Pull request by mdmohsin7**
## Summary by CodeRabbit

- **New Features**
	- Introduced a webhook feature for memory creation, enhancing integration capabilities.
	- Added user prompts for configuring webhook URLs in developer settings.

- **Bug Fixes**
	- Improved error handling and user feedback during webhook integration processes.

- **UI Enhancements**
	- Updated UI components to include loading indicators for a smoother user experience.

### CODE REVIEW

**Comment by beastoin** [comment]
@mdmohsin7 man, who removed it and why ? please clarify before take action to avoid unnecessary conflicts.

**Comment by beastoin** [comment]
*dont need to share it to me

**Comment by mdmohsin7** [comment]
> @mdmohsin7 man, who removed it and why ? please clarify before take action to avoid unnecessary conflicts.

My bad I thought you were aware of it haha. It was removed by Joan in the last release. After that we started receiving a few complains on Discord and Instabug that they are not able to access this feature. So adding it back since people do use it.

**Comment by beastoin** [comment]
Do you discuss with Joan ?

**Comment by mdmohsin7** [comment]
> Do you discuss with Joan ?

Let me. @josancamon19 your input bro?

**Comment by beastoin** [comment]
lgtm 🚀

**Pull request merged**
