### PR TITLE
Fix reported issues

### PR DESCRIPTION
**Pull request by mdmohsin7**
- [x] Bottom floating tab bar text overflows 
- [x] After opening developer settings, sometimes it takes a while for the values entered previously (webook urls) to load. It looks empty at that time
- [x] When not paired the device says null (regression)
- [x] it's pretty hard to press the "clear chat" button because the hitbox is small
- [x] Rate limit exceeded (plugin analytics)
- [x] Remove GCS from developer mode
- [x] Device settings not accessible from connected device page, but are accessible when device is not connected
- [x] Improve getDeviceInfo calls
- [x] Send failed message to user whenever the message endpoints return something other than 200

## Release Notes

- **New Features**
	- Enhanced error handling in message sending with improved logging and crash reporting.
	- Added new properties for developer settings and webhook configurations.
	- Introduced `DeveloperModeProvider` for managing developer settings.
	- New `AppBarWithBanner` widget for improved app bar functionality.

- **Improvements**
	- Streamlined device information retrieval and error handling.
	- Improved UI interactions, including better touch targets for buttons.
	- Enhanced memory-related components with improved loading state handling.
	- Updated logic for displaying charging articles based on device type.
	- Improved layout and organization of preferences and settings pages.

- **Bug Fixes**
	- Corrected provider naming from `CalenderProvider` to `CalendarProvider`.

### CODE REVIEW

**Comment by beastoin** [comment]
resolve *conflicts pls sir @mdmohsin7

**Comment by mdmohsin7** [comment]
> resolve *conflicts pls sir @mdmohsin7

Done sir

**Comment by beastoin** [comment]
@Neotastisch man, have you tested this PR yet ?

**Comment by neooriginal** [comment]
@beastoin not tested, but looked over it. Looked good to me

**Comment by beastoin** [comment]
> @beastoin not tested, but looked over it. Looked good to me

man, test it please :)

**Comment by neooriginal** [comment]
> > @beastoin not tested, but looked over it. Looked good to me
> 
> man, test it please :)

Can’t, not home and not on Mac/Linux

**Comment by beastoin** [comment]
no rush, just 1 rule: if you can't see it how works so don't need to take the responsibility on approving the PR.

**Comment by neooriginal** [comment]
> no rush, just 1 rule: if you can't see it how works so don't need to take the responsibility on approving the PR.

Ok, will keep it mind next time. Sry

**Comment by beastoin** [comment]
lgtm 🥳

**Pull request merged**
