### PR TITLE
added doordash plugin

### PR DESCRIPTION
**Pull request by merouanezouaid**
#488

ty for mentioning the issue -- api keys revoked (my bad)

here's a video link for demo: https://youtu.be/O5rCWoDozyw

### CODE REVIEW

**Review by josancamon19 — CHANGES_REQUESTED** [review]
Does it work with local=False?
It shouldnt trigger a visible UI then, please share code logs.

Also, pls check plugin docs, and submit as a plugin.

**Comment by merouanezouaid** [comment]
image

this is probably either a prompt 'cmd' issue that needs to be improved ( tried giving it step by step instructions )
or that multion can't really make it to the end with local=False (it works so well with local=True, i changed only the parameter)

**Comment by josancamon19** [comment]
Hi @merouanezouaid as you already have experience using multion, would you like taking this? https://github.com/BasedHardware/Omi/issues/653 as a prerequisite for the this PR? Multion team will share more details on the ticket, but basically is to integrate oauth through a multion plugin

**Comment by merouanezouaid** [comment]
okay sounds good!

**Comment by josancamon19** [comment]
Hi @merouanezouaid Multion team took on the task, and we are releasing it later today, they have released already aoauth functionality, I will share how it is working, with this we should be able to integrate doordash if you still want to work on it.

https://share.icloud.com/photos/006OwPb_6Me0M_UZkuOlK_SNQ

**Comment by merouanezouaid** [comment]
okay imma adapt it to doordash

can i add my service in mution or should i wait for them to release it?  i don't think they released docs for third-party services integration yet..
(i can only see amazon in https://multion--friend-demo-fastapi-app.modal.run/)

image

**Comment by nassarhayat** [comment]
We don't currently support doordash. Coming soon. 

Are there other flows you can build on our current list of supported services?

- uber 
- Amazon 
- LinkedIn 
- Instagram 
- facebook 
- delta 
- united airlines 
- resy
- Instacart 
- GitHub 
- OpenTable

**Comment by merouanezouaid** [comment]
@nassarhayat thank you!

i can go with uber, since it's the closest thing to what i've been working on for doordash

there is already an issue to it #489 ... @josancamon19 is there anyone assigned to it? otherwise i can take it :)

**Pull request closed without merging**
