### PR TITLE
Paid Apps handling and creation on the mobile side

### PR DESCRIPTION
**Pull request by mdmohsin7**
- [x] Add the paid/free and $ per month configuration to the app creator page and backend update
- [x] Display $ per month instead of "Install App"
- [x] Show $ per month in the app list
- [x] Navigate to the Stripe payment link to make a payment. Automatically check the payment status every 3-5 seconds, only when the user clicks the Stripe link ($/month)

Part of #1404 

https://github.com/user-attachments/assets/451832e9-35ca-48be-b836-39f31d1571a9

### CODE REVIEW

**Comment by beastoin** [comment]
1/ a toggle to switch the app Free <> Paid and, only display payment plan, pricing with the paid app, what do you think man?
2/ you could use `is_user_paid` in the app model to determine if use paid the app successful or not. about the trigger 3-5s, don't wait for the payment_link, you could use a mock timer to implement it.

@mdmohsin7

**Comment by beastoin** [comment]
3/ keep monthly recurring as the only option for now.

@mdmohsin7

**Comment by mdmohsin7** [comment]
1/ thought of it, but that would be an additional item in the ui so instead thought of just adding a single amount field, if it's empty then it will be considered free. But I guess I'll just add the paid/free dropdown
2/ Alright
3/ Alright

@beastoin

**Comment by beastoin** [comment]
Screenshot 2024-12-10 at 18 56 36
Screenshot 2024-12-10 at 18 22 25

**Comment by beastoin** [comment]
@mdmohsin7 the api is ready on the development env, please integrate it with your PR. 😌

**Comment by mdmohsin7** [comment]
> @mdmohsin7 the api is ready on the development env, please integrate it with your PR. 😌

Alright let me

Also I like how you are using that image everywhere haha

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳

**Pull request merged**
