### PR TITLE
[Plugin Request] Added SOS- Emergency Alert Plugin for OMI

### PR DESCRIPTION
**Pull request by shreybirmiwal**
SOS detects when the user is in danger 'say SOS' and it automatically sends a message to emergency contacts.

Code: https://github.com/[shreybirmiwal/SOS](https://github.com/shreybirmiwal/SOS)

Very much experimental. Wanted to ship V1 and then iterate quickly rather than wait to push this out.

## Summary by CodeRabbit

- **New Features**
  - Introduced the "SOS-Emergency Help" plugin to alert authorities and emergency contacts in dangerous situations.
  - Added setup instructions for the SOS plugin, including authentication and operational guidance.

- **Documentation**
  - Updated the README.md for the SOS plugin with detailed setup steps and a troubleshooting section.

### CODE REVIEW

**Comment by beastoin** [comment]
man @shreybirmiwal why use memory_creation instead of transcript_processed ~ more real-time :?

**Comment by shreybirmiwal** [comment]
> man @shreybirmiwal why use memory_creation instead of transcript_processed ~ more real-time :?

@beatoin
1. No geolocation included in transcript_processed
2. Working on it next - just had some issues piecing together the users whole conversation from sessionID. Will do next is the  plan

Do you have more feedback though. I think its a cool idea and with some improvements could be really useful
Thanks Thinh

**Comment by kodjima33** [comment]
@shreybirmiwal if you add location to transcript_processed => we will add it to codebase

also sent you DM on X, let's chat sometime => i love chatting with people who get stuff done

---
@beastoin can we merge this?

**Review by beastoin — APPROVED** [review]

**Comment by beastoin** [comment]
ofc bruh

**Comment by beastoin** [comment]
@shreybirmiwal could you please use the latest Omi app(iOS/Android) to submit your cool app ? lmk when you've finished it.

**Comment by shreybirmiwal** [comment]
> @shreybirmiwal could you please use the latest Omi app(iOS/Android) to submit your cool app ? lmk when you've finished it.

What does this mean sorry: 
Submit app? You mean test ?

**Comment by shreybirmiwal** [comment]
Oh shoot I understand mb , didn't realize you can submit apps through the app now

**Comment by shreybirmiwal** [comment]
> @shreybirmiwal if you add location to transcript_processed => we will add it to codebase
> 
> 
> 
> also sent you DM on X, let's chat sometime => i love chatting with people who get stuff done
> 
> 
> 
> ---
> 
> @beastoin can we merge this?

Yessir I'll work on adding location to transcript processed asap
And thanks for dm

**Comment by shreybirmiwal** [comment]
> @shreybirmiwal could you please use the latest Omi app(iOS/Android) to submit your cool app ? lmk when you've finished it.

@beastoin @kodjima33 Sure thanks
Do you know what to put for the 'setup instructions URL'
Should I reference the github instructions page: https://github.com/BasedHardware/omi/tree/main/plugins/instructions/SOS


The problem is that the new way of adding a 'setup instructions' is that no URL appends UID at the end. So I cannot give the user a link with UID appended of authentication. It's just a hardcoded link

**Comment by beastoin** [comment]
Use this for now https://github.com/BasedHardware/omi/blob/main/plugins/instructions/SOS/README.md , we would support the plain text / markdown / html later

@shreybirmiwal

**Comment by mdmohsin7** [comment]
@shreybirmiwal approved the app, should be live for everyone

**Comment by shreybirmiwal** [comment]
> Use this for now https://github.com/BasedHardware/omi/blob/main/plugins/instructions/SOS/README.md , we would support the plain text / markdown / html later
> 
> 
> 
> @shreybirmiwal 

The problem is this: when a new user clicks on the instructions, and then clicks on the authentication link, they can't authenticate properly, because no ?uid is appended to the url 

Thus they cannot link their uid and their emergency contact through the authentication page

@beastoin

**Pull request merged**
