### PR TITLE
Add OTA support for Omi DevKit 2

### PR DESCRIPTION
**Pull request by vishwamartur**
Related to #1393

Add OTA firmware update support for Omi DevKit 2.

* **Configuration Changes:**
  - Update `Friend/firmware/firmware_v1.0/prj_xiao_ble_sense_devkitv2-adafruit.conf` to include OTA support settings.
  - Set `CONFIG_BOOTLOADER_MCUBOOT` and `CONFIG_MCUBOOT_SERIAL` to `y`.

* **Documentation Updates:**
  - Add OTA update instructions for Omi DevKit 2 in `Friend/firmware/firmware_v1.0/README.rst`.
  - Update `docs/docs/developer/DevKit2Testing.md` with steps for testing OTA updates.
  - Update `docs/docs/hardware/DevKit2.mdx` with instructions for performing OTA updates.

* **Build Configuration:**
  - Update `Friend/firmware/firmware_v1.0/CMakePresets.json` to include OTA update support for Omi DevKit 2.

### CODE REVIEW

**Comment by beastoin** [comment]
hey @vishwamartur cool!

i just finished this ticket by https://github.com/BasedHardware/omi/issues/1393

with your PR, may i ask why do we need to set configurations CONFIG_BOOTLOADER_MCUBOOT and CONFIG_MCUBOOT_SERIAL ?
 
>Set CONFIG_BOOTLOADER_MCUBOOT and CONFIG_MCUBOOT_SERIAL to y.

**Comment by francip** [comment]
If you want us to have an MCU bootloader based firmware, can you create a new configuration instead of changing the Adafruit bootloader one?
What is the advantage of using MCU bootloader vs Adafruit bootloader?

**Comment by vishwamartur** [comment]
@francip 
<html><head></head><body>

Aspect | MCU Bootloader | Adafruit Bootloader
-- | -- | --
Support | Provided by the MCU manufacturer, with official documentation and tools. | Supported by Adafruit community; great for Adafruit boards.
Ease of Use | Requires manufacturer tools (e.g., STM32CubeProgrammer, MCUXpresso). | Drag-and-drop firmware updates using the UF2 format.
Customizability | Highly customizable for advanced use cases like secure boot and hardware init. | Open-source and extensible, but designed for simplicity.
Security | Supports advanced features like secure boot, cryptographic validation, etc. | Minimal security features; not designed for high-security applications.
Hardware Support | Optimized for MCU-specific hardware (UART, SPI, I2C, USB, CAN, etc.). | Primarily focused on USB-based communication.
Performance | Optimized for minimal flash and RAM usage. | Simpler, but less optimized for constrained environments.
Toolchain | Seamlessly integrates with manufacturer-provided development tools. | Independent of manufacturer tools, works on any USB-compatible system.
Prototyping | Best for professional-grade projects and production use cases. | Excellent for quick prototyping, hobby, and educational projects.
Community Support | Backed by the MCU manufacturer’s ecosystem. | Strong support from the Adafruit community.
Target Audience | Professionals and production engineers. | Makers, hobbyists, and educators.


</body></html>

**Comment by vishwamartur** [comment]
Hi @francip,

Thanks for the feedback! You’re right—creating a new configuration for MCUboot-based firmware makes more sense to avoid affecting the Adafruit bootloader setup. I'll make that change.

As for advantages, MCUboot offers secure boot, image verification, A/B partitioning for OTA reliability, and rollback mechanisms, making it a solid choice for secure and flexible firmware updates.

**Comment by francip** [comment]
Keep this PR alive for a bit, we might need to switch to MCUboot, but please update it to create a new configuration.

**Comment by vishwamartur** [comment]
https://github.com/BasedHardware/omi/pull/1490

MCUboot configuration has been added. Please review it, and I am open to fixing any issues and updating the required changes.

The code has not been tested. Please conduct end-to-end testing on your side. If changes are required, please let me know, and I will work on them.

**Comment by beastoin** [comment]
moved to https://github.com/BasedHardware/omi/pull/1490

**Pull request closed without merging**
