### PR TITLE
Adding time stamps [Add timestamp to Chat #1275]

### LINKED ISSUE #1275: Add timestamp to Chat
Currently, when you go to chat, there are no timestamps. This was fine when you were interacting with the chat directly or looking at the end-of-the-day log. However, now that Omi is logging notifications in the chat, it would be helpful to timestamp those. This way, if you go back, you can easily see when the notification occurred and what the message was.

### PR DESCRIPTION
**Pull request by sanjayamirthraj**
Closes #1275

### CODE REVIEW

**Comment by sanjayamirthraj** [comment]
@mdmohsin7 can you tag this with the proper issue; I am not able to

**Comment by beastoin** [comment]
resolve conflicts again @mdmohsin7 man haha, and, how does it look ? 1 screenshot / video demo would be great ~

**Comment by mdmohsin7** [comment]
@beastoin 

https://github.com/user-attachments/assets/49a85a91-3ede-4d33-be01-c1e84d1dfbab

**Comment by beastoin** [comment]
Screenshot 2024-11-28 at 10 54 37
🧎

**Comment by beastoin** [comment]
1/ sry but Screenshot 2024-11-28 at 10 57 05

@mdmohsin7

**Comment by mdmohsin7** [comment]
Let me fix it. can't see much on small screen haha

**Comment by mdmohsin7** [comment]
Removed padding, pls check now @beastoin

**Comment by beastoin** [comment]
i trust your code @mdmohsin7 / lgtm 🥳

**Pull request merged**
