### PR TITLE
onboard memory storage

### PR DESCRIPTION
**Pull request by Gashpid**

### CODE REVIEW

**Comment by francip** [comment]
@Gashpid have you actually tried building this one?

**Comment by Gashpid** [comment]
@francip Yes, I'm finishing the development.

**Comment by ebowwa** [comment]
Hey Folks, 

so we've tested this over multiple devices and with many recompilings and we have some work to do!

the two biggest issues:

- LEDs
- Pairing

Gashpid has been hard at work with this for awhile, but also developed this as an isolated copy of the codebase so much will need to be refactored and pulled from the current codebase to fully integrate this

**Comment by Gashpid** [comment]
Hi @ebowwa,

I'm currently working on the App so that the connection is successful. On the other hand, I don't know about the pairing problem, since the device does connect correctly, but it's not transmitting the audio as before. In order for it to work with the micro SD card, I had to modify a little the logic of how it starts transmitting the data, so the application has to send a verification value to the device so that it starts transmitting. That may be the problem you're having (which is not a problem but a change in the logic at the start of audio transmission in normal mode).

However, I'm going to make a change in the firmware so that it connects and transmits the audio as it has been doing in past versions under the condition that the micro SD card is not connected; this will help you to perform tests with other modules that you are working on while I finishing modifying part of the App code so that the firmware update is accepted by the App.

**Comment by ebowwa** [comment]
please stash and pull

**Comment by kevvz** [comment]
Does this still work?

**Comment by josancamon19** [comment]
Discarded

**Pull request closed without merging**
