### PR TITLE
Add App/Plugin frontend and backend

### LINKED ISSUE #1128: A simple way to add/submit apps (plugins)
**Is your feature request related to a problem? Please describe.**
People want to be able to test their plugins on their local mobile phone without the need to build the app. 
I went on multiple omi hackathons recently and people were really frustrated with the fact that they need to wait until someone approves their plugin to test on the mobile app. 
Currently, there is no option to test my own plugin in the app without forking and building locally. 

**Describe the solution you'd like**
We need to build a simple form that would allow people to submit their apps through the form. We can host the form on the web / in the omi app. Once submitted, the submitted app should be available to test locally RIGHT AWAY in omi. However, the app will not be available for all users right away and Omi team will need to review it (like we do it now in community plugins) 
- available for submitter right away
- available for everyone else once approved by omi team

### PR DESCRIPTION
**Pull request by mdmohsin7**
Closes #1128 

- [x] Add app functionality on the front and also improve it
- [x] Routes to perform basic operations (add/delete/update/change-visibility)
- [x] New routes for plugins for chat
- [x] Upload logos to GCS bucket
- [x] Script to move plugins from json file to firebase
- [x] Make triggers work
- [x] Ensure backwards compatibility
- [x] Test chat, memory, external integration plugins

**Note: Before deploying these changes, migrate the plugins again (after deleting the plugins_data collection and also the images in the bucket) to have fresh and new copy of data and images**

https://github.com/user-attachments/assets/76d5da73-70d8-4cb6-9fef-ab6cfc29e14d

https://github.com/user-attachments/assets/3452369c-5641-4276-b9a6-5a7335bd57b6

## Release Notes

- **New Features**
  - Introduced a new page for submitting app details, including form validation and image upload capabilities.
  - Added functionality to fetch app categories and trigger events.
  - Implemented a confirmation dialog for app submissions based on user preferences.
  - Enhanced app listing to display privacy status directly in the UI.
  - Added a new snackbar method for displaying success messages.
  - Integrated a new plugin management system with enhanced functionality for adding and retrieving plugins.

- **Bug Fixes**
  - Improved error handling for app enabling and integration processes.
  - Refined navigation logic for integration instructions.
  - Enhanced feedback for unavailable apps in the UI.

- **Chores**
  - Updated dependencies in the project configuration for enhanced functionality.
  - Cleaned up unused imports and optimized code structure across various files.

### CODE REVIEW

**Comment by beastoin** [comment]
1/ provide steps to deploy please
2/ put omi_plugins bucket name to a constant
3/ why do we need the new route for /messages ?
4/ better api route defination for /unapproved-plugin/public, read some best practice about how to define a good api path.
5/ why do we need the api plugin migration ? would we use it twice or more ?

@mdmohsin7

**Comment by beastoin** [comment]
6/ could we navigate the submit.omi.me to the app? how about our web portal to submit new apps ?

@mdmohsin7 

*i will not edit the previous comment to ensure you dont miss anything as updates wouldnt be sent as a notification.

**Comment by mdmohsin7** [comment]
1/ Same existing backend deploy steps sir
2/ Yes totally forgot to change this
3/ You are right, we shouldn't be needing them (realised after your yesterday's message)
4/ Alright will do
5/ No I only added it temporarily because while this PR is being worked on, more plugins might get added to the json file, so did not remove it completely
6/ Yes we will have to setup deep links for that. Submit form on web portal is also possible, since we have the APIs ready


Will ping you once I make the necessary changes @beastoin

**Comment by mdmohsin7** [comment]
Made the necessary changes, review pls @beastoin

**Comment by beastoin** [comment]
1/ deploy steps, for example:
- create bucket storage
- deploy new backend
- run the plugin migration

please notice about the downtime, try avoiding it.

2/ ok
3/ ok
4/ ok but, 
- post /plugins not /plugins/add
- patch to /plugins/:id/approve not post
- ... please double check another routes

5/ ok, add the auth - admin only and create new ticket to remove it.
6/ do we have it yet ? i mean the web portal. also, we didnt have the deeplink yet - i guess

@mdmohsin7 fighting

**Comment by mdmohsin7** [comment]
1/ Oh got it. It will be like this:

-  Create bucket
- Run the migration command locally (this will upload the logos and also adds the plugins data). Locally because there isn't any requirement for it to be done on prod plus there will be zero downtime
- Deploy the backend

4/ Alright will check and make the necessary changes
5/ I'll do one thing, I'll migrate the data now (since there aren't any open PRs for plugins) and will remove the endpoints
6/ No we don't have the web portal, and yes you are right, the deep link setup isn't there at the moment

@beastoin

**Comment by mdmohsin7** [comment]
All changes are done! Don't have to run the migration script as well. Covered some edge case as well. Final review please @beastoin

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳 

pull the main and leave it a final check. 

rolling out to production in next 2 hours.

**Comment by mdmohsin7** [comment]
Alright will have a final check

**Pull request merged**
