### PR TITLE
Conversation Summaries in the correct language

### PR DESCRIPTION
**Pull request by neooriginal**
Nothing big but a lot of non-english users will be happy ;)

### CODE REVIEW

**Comment by neooriginal** [comment]
Im also working on app translations, will follow in another pr soon

**Comment by josancamon19** [comment]
Did you test it extensively? can you share results in multiple languages? Thanks
Check if summary persist and stuff please, thanks.

**Comment by neooriginal** [comment]
> Did you test it extensively? can you share results in multiple languages? Thanks Check if summary persist and stuff please, thanks.

Should not be a problem since I've changed a total of 10 words in the chatgpt prompt. (Use language English -> use language [Language Code].
Sadly I do not have the backend set up, that's why I cannot test it

**Comment by neooriginal** [comment]
Translations will be added in the future

**Pull request closed without merging**
