### PR TITLE
Textual Reviews for Apps

### LINKED ISSUE #1331: comment section for apps
**Is your feature request related to a problem? Please describe.**
As a developer, im not able to receive feedback for my published omi app, except DMs

**Describe the solution you'd like**
I would like a simple comment/feedback section under my app to receive feedbacks/comments for my app to understand how can I make it better

### PR DESCRIPTION
**Pull request by mdmohsin7**
Closes #1331 

- [x] View and interact with reviews
- [x] Redesigned and new UI for reviews
- [x] Add/Update textual reviews
- [x] Reply to reviews as the app owner
- [x] Migrate reviews to Firestore
- [x] Add/Update reviews simultaneously to both Firestore and Redis whenever they are added/updated
- [x] Update `get_available_apps` to return textual reviews if they exist

Bunch of stuff summarized in above points

https://github.com/user-attachments/assets/8cde8b28-06e4-4d32-ba98-4e54e9cf0dee

https://github.com/user-attachments/assets/421c4464-1ac0-415d-a3c1-e636c327b6f9

https://github.com/user-attachments/assets/8f7979ab-5338-4dc4-a823-f8e06c82166b

https://github.com/user-attachments/assets/fa841d35-d14e-4903-a5b3-f676ef1a2da0

### CODE REVIEW

**Comment by mdmohsin7** [comment]
Almost ready for review, just a few minor edge cases that I noticed while recording the video, will fix it tomorrow. @beastoin review time tomorrow 🌚

**Comment by beastoin** [comment]
are you ready man?

**Comment by mdmohsin7** [comment]
> are you ready man?

Yessir

**Comment by beastoin** [comment]
1/ how many review a user could send for an app ?
2/ please list down all new APIs and tell me the reason you naming the route like this, no worries, time to learn
3/ move the logic that needs write to the database to util > app, don't put it to the router directly.

@mdmohsin7 ^

**Comment by mdmohsin7** [comment]
1\ I'm not sure if I understand your question correctly, a user can review an app only once but they can always update the review. App owners cannot review their own app
2\  
- PATCH v1/apps/{app_id}/review: this is to update an existing review
- PATCH v1/apps/{app_id}/review/reply: this is for the app creator to reply to reviews
- GET v1/apps/{app_id}/reviews: this is to return all the reviews of a specific app (not used now, but once we have enough reviews, we will use this to return reviews for the reviews list and the app data will only include most recent 4-5 reviews to keep the request size low)
- GET /get-review: this was while testing, forgot to remove. Removing it now. I was having issues with routes not working correctly locally hence named it that way. Will be removed
- GET v1/update-review: same as above, forgot to clean. Removing it now

3\ Yes the write logic happens in  util only in `set_app_review`. This function in util will update/add the review in both firestore and redis

@beastoin

**Comment by mdmohsin7** [comment]
Resolved conflicts and also cleaned up unused stuff @beastoin

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳

**Pull request merged**
