### PR TITLE
Added Friend Speaker Support and Buzzer #567 #573

### PR DESCRIPTION
**Pull request by kevvz**
#567 

How to test:
In the firmware_v1.0 file,
- Flash the zephyr.uf2 file in the file "build_speaker". 
-Then use the script "discover_devices.py" to find the device id of your Omi device. This is to avoid cases where there are multiple friends connected at once. If there is more than one friend then just test all of them.

In the script play_sound_on_friend.py, (in firmware_v1.0)
- On line 20 add the device id of your friend. This is to avoid cases where there is more than one friend nearby.
- On line 21 add your Deepgram API key.

Then save and run the script by typing a small string. For example, one line could be

python3 play_sound_on_friend.py "hello"

Which should get the speaker to say hello. Make sure your device is connected by USB or you have connected a 3.3V pin to the speaker.

#573  (For now it is disabled but since this uses very similar code). 

A sound should play automatically when you compile and run the zephyr.uf2 file. Of course this file can be modified to play any haptic sound provided you enter the appropriate lookup table.

### CODE REVIEW

**Review by kevvz — COMMENTED** [review]
done

**Comment by kodjima33** [comment]
@kevvz 
Tried but didn't work for me

How I tested: 
1. installed firmware
2. added deepgram key
3. opened light-blue app on phone and copied uuid of friend
4. added uuid on line 25
5. got the following error
CleanShot 2024-08-24 at 14 36 54

6. tried to put same uuid on line 111 
same result

**Comment by kodjima33** [comment]
CleanShot 2024-08-24 at 15 28 57
@kevvz saw the update but get same error - may be I'm doing something wrong

**Comment by kevvz** [comment]
> @kevvz Tried but didn't work for me
> 
> How I tested:
> 
> 1. installed firmware
> 2. added deepgram key
> 3. opened light-blue app on phone and copied uuid of friend
> 4. added uuid on line 25
> 5. got the following error
>    CleanShot 2024-08-24 at 14 36 54
> 6. tried to put same uuid on line 111
>    same result

The device id you are using for connection is the battery service, no? Please use the script labeled "discover_devices.py" to find your device id.

**Comment by kodjima33** [comment]
@kevvz saw your update -  but still didn't work for me

Note: Im using python (not python3) and getting uuid from light-blue - may be im doing something wrong?
CleanShot 2024-08-24 at 15 34 37

**Comment by kevvz** [comment]
It looks like a mistake on my part now. The bluetooth advertising appeared to stop working, so I changed some directives in the config and its files and recompiled. The updated zephyr file should work. To be sure I copied that build into my device, and then tested using only the play_sound_on_friend.py file. If it doesn't work now then restart the bluetooth option on your Mac and make sure your device id is what is actually there.

**Comment by kevvz** [comment]
Moving this to another PR #686

**Pull request closed without merging**
