### PR TITLE
Count usage and money from 1st nov and fix for new apps

### PR DESCRIPTION
**Pull request by mdmohsin7**
- [x] Start usage and money count from Nov 1st only
- [x] Fix usage and money not working for new apps

### CODE REVIEW

**Review by mrlfarano — APPROVED** [review]
lgtm

**Comment by beastoin** [comment]
1/ wrap the logic of get_plugin_usage_history + date filter(item.timestamp.date() < datetime(2024, 11, 1)...) to util then call it from router.
2/ add the cache first to these APIs, use redis, ttl 5m
3/ recheck the logic `item.timestamp.date() < datetime(2024, 11, 1).date():` notice the timezone?

@mdmohsin7

**Comment by mdmohsin7** [comment]
Alright let me

**Comment by mdmohsin7** [comment]
Pls review @beastoin

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳


4/ you could also filter the date directly at https://github.com/BasedHardware/omi/pull/1358/files#diff-6a4c2c7ecc69146760e88741b9b4993cf1b06de4ae8da18a98db00601641708bR134 :)

**Pull request merged**
