### PR TITLE
Improve Apps

### PR DESCRIPTION
**Pull request by mdmohsin7**
- [x] Change visibility on the go
- [x] Delete App
- [x] Edit/Update App
- [x] Improve endpoints logic
- [x] Notification on App status change
- [x] Change Add app UI (also include new triggers)
- [x] Improve app detail UI
- [x] Restructure stuff
- [x] Setup instruction text or link
- [x] App review status indicator
- [x] Create App Model to simplify things
- [ ] Simplify external integration steps (probably later)

I guess I am missing few more things which I did already :/

https://github.com/user-attachments/assets/401d93f0-e6a2-4c33-9e3c-4487d7d61a80

### CODE REVIEW

**Comment by beastoin** [comment]
wohoo looking fwd

**Comment by beastoin** [comment]
1/ I understand that you created the new set of App including router, util, database, model to perform new fields / new logic for Plugin. It would be great if you could merge the model, util, database for app and plugin so that we don't have to maintain 2 objects at the same time. 

2/ /v1/notification-scopes, you could change to /v1/plugin|app/proactive-notification-scopes

3/ is_public_plugin_owner_db unused?

@mdmohsin7 have a nice weekend & take your time 🏄‍♀️

**Comment by mdmohsin7** [comment]
1/ I was thinking of merging them after a week or two so that the backend is backwards compatible. What do you suggest?
2/ Alright will make the change
3/ Yes not needed anymore

@beastoin no weekends when you want to build a great product haha

**Comment by beastoin** [comment]
1/ what do you mean by `so that the backend is backwards compatible.` man :? 
2/ ok
3/ ok

@mdmohsin7

**Comment by mdmohsin7** [comment]
1/ I mean the old versions of the app work without issues

I'll do one thing, I'll replace all the remaining plugin endpoints in the app with apps endpoints. So it will be a lot less work in future to remove the unused endpoints

@beastoin

**Comment by kodjima33** [comment]
Need apps editing in prod asap

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳 , pls add +1 ticket to merge 2 terms app / plugin + should be done in the next 2 weeks

**Pull request merged**
