### PR TITLE
Deep sleep Improved

### PR DESCRIPTION
**Pull request by kevvz**
We use system off and manual device turnoffs to further reduce battery drainage. This PR also considers cases where you plug in with the usb, press the button, etc. Now, when you press the button after you long press, it will activate the device rather than turning it on when long pressing.

Issue: #1193

## Release Notes

- **New Features**
  - Added I2C configuration for the LSM6DS3TR-C sensor.
  - Introduced functions to control the power state of the microphone and SD card.
  - Added Bluetooth control functionality with `bt_off()` for enhanced transport management.
  - New function `activate_everything_no_lights()` for component initialization without LED activation.

- **Improvements**
  - Enhanced button handling with power management features.
  - Reduced memory allocation size for audio processing in the speaker functionality.
  - Improved battery management and accelerometer data handling.
  - Enhanced USB disconnection handling with new control flow.

- **Bug Fixes**
  - Streamlined button state transitions and error handling.

These updates enhance device functionality, optimize resource management, and improve user experience.

### CODE REVIEW

**Comment by hoai265** [comment]
Hi @kevvz i try your code with my unoffical dev kit v2 and the system only reach about 4.4mA.
IMG_4304
Could you double check?

**Comment by hoai265** [comment]
image

**Comment by kevvz** [comment]
> image

Hi, the newest dev kit, with the custom PCB, has an sd enable pin and a mic pin which I suspect contributes to the power drain. Here is the picture of the multimeter I used to connect to the battery.

**Comment by hoai265** [comment]
Ok @kevvz , I will test and confirm on the official one when i received. Still waiting for it :(. Btw could you also power down the accelerometer? it will reduce about 0.15mA i think.

**Comment by kevvz** [comment]
> Ok @kevvz , I will test and confirm on the official one when i received. Still waiting for it :(. Btw could you also power down the accelerometer? it will reduce about 0.15mA i think.

New record!!

**Comment by beastoin** [comment]
cool! please keep collaborating. looking fwd for the next firemware release. feel free to lmk when the code is ready to be merged.

**Comment by hoai265** [comment]
Hi @kevvz, I love the new record! Could you check and confirm the actual code changes that reduced power consumption? For example, changes in the .conf or .overlay files... That will help us identify and confirm the root causes.

**Comment by beastoin** [comment]
mans @kevvz @hoai265 , any updates ? should i merge it 😏

**Comment by vincentkoc** [comment]
This might explain some of heat i get on the "unofficial" red devkit2 - awesome work.

**Comment by beastoin** [comment]
@vincentkoc have you try compiling the firmware code yet?

**Comment by vincentkoc** [comment]
@beastoin im happy to test in 5 hours or so, i wont flash my device as im worried it could brick and only have 1 for testing / firmware updates

**Comment by vincentkoc** [comment]
@beastoin build succeeded - fyi overlay file was wrong (not sure if my PR was merged or this PR was not rebased). 

image

There are a LOT of warnings and same stuff CodeRabbit has picked up which would be great to clean-up.

**Comment by beastoin** [comment]
@vincentkoc super happy to send you a dk2. discord dm pls sir / thank you 💪

**Comment by beastoin** [comment]
preparing for the merge.

**Pull request merged**
