### PR TITLE
Plugins to Apps merging and improvements

### PR DESCRIPTION
**Pull request by mdmohsin7**
- [x] Check if app.uid == uid when increasing/decreasing install count to not record app owner installs
- [x] Rename plugin to app in a lot of places and clean
- [x] Duplicate `record_plugin_usage` as `record_app_usage` and use this everywhere
- [x] Add uid check while recording app usage (to not record private apps usage or app owner usage)

### CODE REVIEW

**Comment by beastoin** [comment]
1/ do we need to change the app's api request params after changing the router ? plugin_id is now app_id
Screenshot 2024-11-28 at 10 41 19

@mdmohsin7 ^

**Comment by mdmohsin7** [comment]
> 1/ do we need to change the app's api request params after changing the router ? plugin_id is now app_id

This is a mistake, shouldn't have been done in this PR. Let me revert it, and also will cross check all the changes once again

@beastoin

**Comment by mdmohsin7** [comment]
Pls check now @beastoin

**Comment by beastoin** [comment]
1/ ok ✅
2/ your logic looks weird man, simply put `if x is none or x == y then increase_count.` (btw non block - you could fix it later)
Screenshot 2024-11-29 at 08 45 54
3/ resolve conflicts again haha 

@mdmohsin7

**Comment by mdmohsin7** [comment]
Done @beastoin

**Comment by beastoin** [comment]
oops again @mdmohsin7 , 1-by-1, pls resolve conflict then ping me 😌

**Comment by mdmohsin7** [comment]
Check again @beastoin, hopefully this is the last conflict

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳

**Pull request merged**
