### PR TITLE
Added new Participant Analysis plugin

### PR DESCRIPTION
**Pull request by findirfin**
added a plugin that lists information about people in the conversation to make it easy to remember people. I also added an icon for this plugin. 

## Summary by CodeRabbit

- **New Features**
	- Introduced the "Participant Analysis" plugin for analyzing conversation transcripts, focusing on speakers and mentioned individuals.
- **Bug Fixes**
	- Removed the "Psychologist" plugin from the list of available plugins.

### CODE REVIEW

**Comment by findirfin** [comment]
I changed the plugin image to be a .jpg. also, the AI is saying the I removed the "Psychologist" plugin, but I don't think I did...

**Comment by beastoin** [comment]
this is a good idea. 

btw at the moment, the speaker indentification in Memory is not a good enough. would be great if you could help with that problem.

by that way, your plugin would be more useful.

feel free to contact me https://discord.gg/based-hardware-1192313062041067520

**Comment by findirfin** [comment]
> feel free to contact me https://discord.gg/based-hardware-1192313062041067520

Sent you a dm

**Comment by mdmohsin7** [comment]
Hi @beastoin @findirfin, is this up to be merged or are there any other plans?

**Pull request closed without merging**
