### PR TITLE
bug: status showing reconnecting while listening

### PR DESCRIPTION
**Pull request by ARYPROGRAMMER**
This PR successfully fixes the Issue #1428 

No Other File was altered, all tests pass and not a breaking change

### CODE REVIEW

**Review by mdmohsin7 — CHANGES_REQUESTED** [review]
Hi @ARYPROGRAMMER, this isn't actually a fix. This would show `Listening` even when there's no internet or the transcript service is down, which isn't the ideal scenario

**Comment by ARYPROGRAMMER** [comment]
@mdmohsin7 please review now and let me know further

**Review by mdmohsin7 — CHANGES_REQUESTED** [review]
These changes as well do not fix the issue. Pls revert the `getPhoneMicRecordingButton` changes as they are unrelated and they would result in `Initialising Recorder` not being shown when the user clicks on `Try with Phone Mic`. The mic recorder takes a few seconds to initialise, and this state being omitted will result in user assuming the feature isn't working because there's no visible transcript for a few seconds (until the recorder is initialised)

**Comment by beastoin** [comment]
@ARYPROGRAMMER could you share with me:

1/ what are your finding so far ? - to ensure you understand about the current issue.
2/ your tests - to confirm the issue has been fixed and nothing else has been broken as far as you know.

happy coding.

**Comment by beastoin** [comment]
1w, no response

**Pull request closed without merging**
