### PR TITLE
replace whisper with deepgram for testing

### PR DESCRIPTION
**Pull request by Bentlybro**
# dont merge this, its just for testing

### CODE REVIEW

**Comment by DamienDeepgram** [comment]
There is a fork here with real time streaming with Deepgram implemented

https://github.com/DamienDeepgram/Friend

**Comment by Wladefant** [comment]
The next step then would be to let the user choose, between whisper and deepgram, which means implement the things @DamienDeepgram into the main flutter app directly

**Comment by Wladefant** [comment]
seems to be integrated now

**Comment by Bentlybro** [comment]
will close this then as its not needed, was supposed to be just an idea/for testing

**Pull request closed without merging**
