### PR TITLE
Restructure id logic and move private apps to plugins_data collection

### PR DESCRIPTION
**Pull request by mdmohsin7**
- [x] Use ULID for ID
- [x] Store private and public plugins in `plugin_data`
- [x] Migrate existing private plugins to `plugin_data`
- [x] Cleanup some of the unused functions
- [x] Redirect some of the plugins endpoints to use apps functions
- [x] Fix analytics for new apps
- [x] Test with old and new apps

Part of #1290

### CODE REVIEW

**Comment by beastoin** [comment]
man, for the auto generated id, pls use:
1/ slugify
2/ if existed, + ulid
3/ should have the length limits(min/max)

@mdmohsin7

**Comment by mdmohsin7** [comment]
1/ Yes slugifying it
2/ If id already exists, then I'm appending 5 random numbers to it at the end. adding ulid makes more sense
3/ minimum 1 works as well. The max will depend on the name of the plugin. We should ideally restrict the name to certain length?

@beastoin

**Comment by mdmohsin7** [comment]
I'll change to use ulid in the next PR, can we have these minor changes merged for now?

**Comment by beastoin** [comment]
1/ find a better implementation pls, too manny failures with your code
2/ ulid is optional, add the incrementing number is good enough.
3/ restrict the id's length pls. min 5 max 128 chars.

@mdmohsin7

**Comment by mdmohsin7** [comment]
1/ Thinking of using this python package for it https://pypi.org/project/python-slugify/
2/ That would mean storing a separate counter or iteratively checking for the incremented id one by one?
3/ Alright will do

@beastoin

**Comment by beastoin** [comment]
1/ good enough
2/ we dont do leetcode here, btw think it a bit more more pls 🌚

@mdmohsin7

**Comment by mdmohsin7** [comment]
2/ I only did one leetcode problem in my life haha. Thinking of storing the most recently incremented id in a firestore collection

**Comment by beastoin** [comment]
2/ our plugin is not that big yet, just count()+1

@mdmohsin7

**Comment by mdmohsin7** [comment]
2/ Oh okay lol. slugified name + doc_count + 1

If the app is private, I am appending `-private` to them. Not making any changes to this btw

**Comment by beastoin** [comment]
4/ please run a test for https://github.com/BasedHardware/omi/pull/1285/files#diff-e9334601001806a62e30da99b753c713c2c20213a661ced0a88542e66e39697eR26 / since i encounter the error with similar code at https://github.com/BasedHardware/omi/pull/1300#issue-2654170539

5/ you could simplify the database > apps by using a wrapper func in utils > app
 - get_available_apps(uid: str|None) -> List<App> to list all not deleted, approved apps + private apps owned by uid
 - get_available_app_by_id(id: str, uid: str|None) -> App to get 01 not deleted, approved app or 01 private app owned by uid

@mdmohsin7

**Comment by mdmohsin7** [comment]
4/ Though I did not get that error when running locally, will try to check
5/ Renaming `get_apps_data_from_db`to `get_available_apps` because it already does the same thing in utils. Creating a new func in utils named `get_available_app_by_id ` which will call `get_app_by_id_db` in db/apps

@beastoin

**Comment by mdmohsin7** [comment]
Did the suggested changes and used BaseCompositeFilter for `AND` filter for multiple where queries @beastoin

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳 pls resolve the code conflict

**Comment by mdmohsin7** [comment]
> lgtm @mdmohsin7 🥳 pls resolve the code conflict

Resolved 🥳

**Pull request merged**
