### PR TITLE
Replace logo appstore playmarket

### PR DESCRIPTION
**Pull request by sanjayamirthraj**
Changed logos to Omi logos

## Summary by CodeRabbit

- **New Features**
	- Introduced an `info` section in asset JSON files, providing metadata like author and version.
  
- **Bug Fixes**
	- Simplified the structure of image entries in the AppIcon asset set, enhancing readability and organization.
  
- **Chores**
	- Updated the filenames in the app icon assets for consistency and standardization.

### CODE REVIEW

**Comment by beastoin** [comment]
better naming pls @sanjayamirthraj

**Comment by beastoin** [comment]
@sanjayamirthraj could you finish this task by a tiniy fix ? rename the files:
- Not good:  Screenshot 2024-11-10 at 15 37 20

- Good enough: Screenshot 2024-11-10 at 15 37 25


Ref: https://developer.apple.com/design/human-interface-guidelines/app-icons

**Comment by mdmohsin7** [comment]
@sanjayamirthraj you can use https://icon.kitchen/ as well to generate the icons with correct names as requested by @beastoin

**Comment by beastoin** [comment]
@mdmohsin7 pls take over it.

**Comment by sanjayamirthraj** [comment]
> @sanjayamirthraj you can use https://icon.kitchen/ as well to generate the icons with correct names as requested by @beastoin

The names are properly changed I believe; this displays properly in local testing

**Comment by beastoin** [comment]
lgtm 🥳 @sanjayamirthraj @mdmohsin7

**Pull request merged**
