### PR TITLE
encapsulate Devices, add Frame glasses audio support

### PR DESCRIPTION
**Pull request by OkGoDoIt**
Implements #532 

Currently only supports audio, will add photos soon.

This affects a lot of files due to re-implementing the way devices are handled.  The new `device.dart` is a base class for all possible devices, with the Friend and Frame being implemented as `BtleDevice.dart`.  Eventually there may be other devices that are not btle.

This is my first contribution and also I'm new to Flutter, so please help me test this thoroughly.

### CODE REVIEW

**Comment by kodjima33** [comment]
@OkGoDoIt 

> IMG_2194

Was able to connect and the frame shows "listening" 

Wasn't able to test transcription as I'm having troubles myself with installing backend

I think it's probably good and I believe you should keep going and try add images as well

**Comment by OkGoDoIt** [comment]
That screenshot is usually what it shows when it pairs to the frame but then disconnects either because the frame has been turned off or gone out of range. When I’m there tonight we can go over the scenario that led to that and figure out how to solve it.

There is also a potential issue if your frame has an old version of the firmware. Right now the only way to update the frame firmware is through the official Noa app, so let’s check that as well. I can add some firmware version checks on my end to improve the experience there as well.

**Comment by mdmohsin7** [comment]
@OkGoDoIt can you please resolve the conflicts? The issue Nik mentioned is resolved on the main branch. Also can you please share a demo working video of Frame with the Omi App? Thanks

**Comment by OkGoDoIt** [comment]
Well it was difficult but I got photos and audio working simultaneously from the Frame!  😎  Still some code cleanup that I need to finish but this is major progress.  Also there's a bunch of merges I need to do too.  I will get to these Thursday.

IMG_1112

**Comment by josancamon19** [comment]
@Becca-Saka will review, and help merging this to match new provider migration.

**Comment by kodjima33** [comment]
@OkGoDoIt can you resolvle conflicts and once done we will merge today?

**Comment by josancamon19** [comment]
Cancelled PR, already merged a cleaner version of this https://github.com/BasedHardware/Omi/pull/687

**Pull request closed without merging**
