### PR TITLE
feat: Added Speaker Support #567 #573

### PR DESCRIPTION
**Pull request by vincentkoc**
* Pin configuration and overlay changes #567
* Added boot sequence audio to test speaker #567
* Added vibrate "haptics" function based on speaker (not great with current speaker, but half works) #573

Note I am worried about memory and buffer, if we are to hook up to BT we need to ensure memory is very well handled overwise can have some issues once SD and other features added.

### CODE REVIEW

**Comment by vincentkoc** [comment]
FYI this PR was ready to merge before #629

**Comment by kevvz** [comment]
I had demoed the vibrator last week and the speaker yesterday to Nik so unfortunately I think the rights to this PR are going to be murky. I also have video footage of the speaker characteristic postmarked at Sunday, which was also a requirement for this.

**Comment by vincentkoc** [comment]
All good, you can have the bounty.

**Comment by kevvz** [comment]
I would still like to have my code roasted :)

**Comment by kodjima33** [comment]
Was able to build, the speaker plays audio when connected. Not sure if there is a characteristic or a python script to send text? @vincentkoc 

cc @josancamon19

**Comment by josancamon19** [comment]
Merged, @kevvz PR, @vincentkoc is there anything here, that we should include in main instead?

**Comment by vincentkoc** [comment]
@kevvz can you add the boot sound sequence to your changes? This is easy to validate everything works as intended on boot and all code works.Sent from my iPhoneOn 29 Aug 2024, at 18:13, Joan Cabezas ***@***.***> wrote:﻿
Merged, @kevvz PR, @vincentkoc is there anything here, that we should include in main instead?

**Comment by josancamon19** [comment]
Merged changes in https://github.com/BasedHardware/Omi/pull/698 Thanks @vincentkoc @kevvz

**Pull request closed without merging**
