### PR TITLE
fix: broken nrf firmware build command

### PR DESCRIPTION
**Pull request by vincentkoc**
Build overlay for v2 has a typo, this corrects so anyone who uses vscode for first time can one click install and build the firmware without issues.

### CODE REVIEW

**Comment by beastoin** [comment]
hi @vincentkoc please tell me more about the typo issue ?

**Comment by vincentkoc** [comment]
@beastoin i worked on all these original config files for the SD card stuff to allow for overlay files for the project.

The `CMakePresets.json` has preset builds and this is referencing the wrong location of the overlay file (typo), probably from one of my earlier commits. I dont use CLI for builds I use NRF toolkit extensions in VScode and this pickups all the configs and allows for one click build

image

This fixes this cmake config overlay file to match the expected filename for the dev2 kit firmware build.

**Review by kevvz — COMMENTED** [review]
good

**Review by kevvz — APPROVED** [review]
merged

**Pull request merged**
